version: '3.8'
services:
  app:
    container_name: symfony-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    env_file:
      - .env.local
    depends_on:
      - database
      - mailhog

  database:
    container_name: database
    image: mysql:5.7
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - 3310:3306
    env_file:
      - .env.local
    user: 1000:1000

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  database_data: {}